# Generated by Django 3.2.18 on 2023-05-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogmod_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmod',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
